#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biegi_rejestracja.Tabela_baza_danych
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Bieg_rejestracja")]
	public partial class lista_startowaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLista_stratowa(Lista_stratowa instance);
    partial void UpdateLista_stratowa(Lista_stratowa instance);
    partial void DeleteLista_stratowa(Lista_stratowa instance);
    #endregion
		
		public lista_startowaDataContext() : 
				base(global::biegi_rejestracja.Properties.Settings.Default.Bieg_rejestracjaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public lista_startowaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lista_startowaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lista_startowaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lista_startowaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Lista_stratowa> Lista_stratowa
		{
			get
			{
				return this.GetTable<Lista_stratowa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Lista stratowa]")]
	public partial class Lista_stratowa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _ID_uczestnika;
		
		private int _ID_biegu;
		
		private int _Numer_startowy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_uczestnikaChanging(int value);
    partial void OnID_uczestnikaChanged();
    partial void OnID_bieguChanging(int value);
    partial void OnID_bieguChanged();
    partial void OnNumer_startowyChanging(int value);
    partial void OnNumer_startowyChanged();
    #endregion
		
		public Lista_stratowa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_uczestnika", DbType="Int NOT NULL")]
		public int ID_uczestnika
		{
			get
			{
				return this._ID_uczestnika;
			}
			set
			{
				if ((this._ID_uczestnika != value))
				{
					this.OnID_uczestnikaChanging(value);
					this.SendPropertyChanging();
					this._ID_uczestnika = value;
					this.SendPropertyChanged("ID_uczestnika");
					this.OnID_uczestnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_biegu", DbType="Int NOT NULL")]
		public int ID_biegu
		{
			get
			{
				return this._ID_biegu;
			}
			set
			{
				if ((this._ID_biegu != value))
				{
					this.OnID_bieguChanging(value);
					this.SendPropertyChanging();
					this._ID_biegu = value;
					this.SendPropertyChanged("ID_biegu");
					this.OnID_bieguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numer_startowy", DbType="Int NOT NULL")]
		public int Numer_startowy
		{
			get
			{
				return this._Numer_startowy;
			}
			set
			{
				if ((this._Numer_startowy != value))
				{
					this.OnNumer_startowyChanging(value);
					this.SendPropertyChanging();
					this._Numer_startowy = value;
					this.SendPropertyChanged("Numer_startowy");
					this.OnNumer_startowyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
