<?xml version="1.0" encoding="utf-8"?><Database Name="Bieg_rejestracja" Class="zawodnikDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-UF4NK14O\SQLEXPRESS;Initial Catalog=Bieg_rejestracja;Integrated Security=True" SettingsObjectName="biegi_rejestracja.Properties.Settings" SettingsPropertyName="Bieg_rejestracjaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Zawodnik" Member="Zawodnik">
    <Type Name="Zawodnik">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Haslo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data_urodzenia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Płeć" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>